steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/cv-data-collection/amar-movies-react:$COMMIT_SHA',
        '--file=./Dockerfile-dev',
        '.',
      ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cv-data-collection/amar-movies-react:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'amar-movies-react',
        '--image',
        'gcr.io/cv-data-collection/amar-movies-react:$COMMIT_SHA',
        '--region',
        'asia-southeast1',
        '--platform',
        'managed',
        '--port',
        '8080',
        '--allow-unauthenticated',
      ]

images:
  - 'gcr.io/cv-data-collection/amar-movies-react:$COMMIT_SHA'
