export const GET_MOVIES = "GET_MOVIES"

export const GET_MOVIES_REQUESTED = "GET_MOVIES_REQUESTED"
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS"
export const GET_MOVIES_FAILED = "GET_MOVIES_FAILED"
